# Generated by Django 5.2.6 on 2025-09-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
