# Generated by Django 5.2.6 on 2025-09-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_organizer_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
