# Generated by Django 5.2.6 on 2025-09-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_racer_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='bio',
            field=models.TextField(default='Hi, I make racing events!', null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='carte_biometrique',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='pfp',
            field=models.ImageField(default='img/pfp.webp', upload_to='pfp'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='tel',
            field=models.CharField(default='+213', max_length=10),
        ),
        migrations.AlterField(
            model_name='racer',
            name='bio',
            field=models.TextField(default='Hi, I love racing!', null=True),
        ),
        migrations.AlterField(
            model_name='racer',
            name='carte_biometrique',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='racer',
            name='date_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='racer',
            name='finished_first',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='racer',
            name='nbr_of_races',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='racer',
            name='pfp',
            field=models.ImageField(null=True, upload_to='pfp'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='podium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='racer',
            name='tel',
            field=models.CharField(default='+213', max_length=10),
        ),
    ]
