# Generated by Django 5.2.6 on 2025-09-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_customuser_email_alter_organizer_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Organizer', 'Organizer'), ('Participant', 'Participant')], default='Participant', max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='place',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='race',
            name='type',
            field=models.CharField(choices=[('Cycling', 'Cycling'), ('Triathlon', 'Triathlon'), ('Marathon', 'Marathon'), ('Swimming', 'Swimming'), ('Crossfit', 'Crossfit'), ('Calisthenics', 'Calisthenics'), ('Rally Racing', 'Rally Racing'), ('Moto GP', 'Moto GP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='racer',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='racer',
            name='speciality',
            field=models.CharField(choices=[('Cycling', 'Cycling'), ('Triathlon', 'Triathlon'), ('Marathon', 'Marathon'), ('Swimming', 'Swimming'), ('Crossfit', 'Crossfit'), ('Calisthenics', 'Calisthenics'), ('Rally Racing', 'Rally Racing'), ('Moto GP', 'Moto GP')], default='Cycling', max_length=20),
        ),
    ]
