# Generated by Django 5.2.6 on 2025-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_customuser_role_alter_race_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
