# Generated by Django 5.2.6 on 2025-10-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_race_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='wilaya',
            field=models.CharField(default='Annaba', max_length=20),
        ),
    ]
