# Generated by Django 5.2.6 on 2025-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_race_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='is_ranked',
            field=models.BooleanField(default=False),
        ),
    ]
