# Generated by Django 5.2.6 on 2025-10-18 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_race_is_ranked'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pages.race')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.racer')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('race', 'racer')},
            },
        ),
    ]
